version: 2.1

workflows:
  test-deploy:
    jobs:
      - test
      - hold:
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - hold
          

jobs:
  test:
    docker:
      - image: cimg/node:14.13.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm run test
  hold:
    docker:
      - image: cimg/node:14:13.0
      
  deploy:
    docker:
      - image: cimg/node:14.13.0
    steps:
      - checkout
      - run: echo 'hello app is deploying'
